### ISSUE TITLE
Monitor/Datalog of EMS Data

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#20]
The EMS is run on an AutomationDirect PLC P2-550.  It is monitoring/measuring some critical values that we would like to datalog during our machining operations.  The two values for logging are for tank 03 (T-03) which stores the clean electrolyte:

1. pH
2. Conductivity

In addition we would like to actively monitor the status of the EMS system.  It has some alarms/error states that we would want to indicate on the front panel GUI of the PECM operating software to alert the user.

The manual can be found here:  https://cdn.automationdirect.com/static/manuals/p2userm/ch6.pdf

It operates on a Modbus data type over ethernet.  We can us the Modbus mapping database in the setup software to assign the registers that need to be read for all of the values requested.  The setup and mapping of the modbus registers will be addressed by Eric Rountree.

**Comment by majorpr13** [comment]
This is completed in the current PLC branch.
