### ISSUE TITLE
Number of pulses in pulse train

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#25]
There is currently no option to set a specific number of pulses when the power supply is enabled. Value should be able to be set between 1 and 255 (255 is continuous).

**Comment by mbromley-voxel** [comment]
It does not seem to be transmitting the updates to Munk.  The transmit progress bar does not do anything upon selecting Transmit.  Will investigate further with the Munk software

**Comment by majorpr13** [comment]
This issue has been addressed and is now transmitted with the segment.

**Comment by mbromley-voxel** [comment]
The command is working, the remaining issue is documented in issue #45
