### ISSUE TITLE
On Time Reporting for Electrolyte Pump

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#26]
The "On Time:" box for the electrolyte pump reports something other than the pump run time.

**Comment by majorpr13** [comment]
The On Time box reflects the time that the pump was turned on to check the 5 second duration. This can reflect another parameter if desired or removed entirely.

**Comment by mbromley-voxel** [comment]
Make this an active counter showing the amount of time that the pump has been running.  It should stop on pump off and be reset before a new run.

**Comment by mbromley-voxel** [comment]
It is working as intended, but no need to display three decimal places.  Make it just a whole number of seconds.

**Comment by mbromley-voxel** [comment]
Validated
