### ISSUE TITLE
Touch off issues

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#27]
"Establish Touchoff" Button is not connected.

"Set Touchoff Ref" box only updates the value in galil when you actually push the button. Pushing the button sets the value to the current location. The value in the box needs to be typed in sometimes so that you don't have to visually set the position, but currently typing in this box will not update galil.

The status of the touchoff does not change from "Touch-off Searching" if the touch off attempt is cancelled.

Can we remove the button "Set Initial Gap" and just have it update on a change like the boxes under "Profile Options."

**Comment by majorpr13** [comment]
This issue request has been decomposed into several other enhancements and bug issues. Namely the following #32 , #33, #34, #35
