### ISSUE TITLE
Encoder Value Plot Stops Working

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#28]
After a touch off is completed, the plot of the encoder position stalls out and takes ~15 seconds to return to activity.

**Comment by majorpr13** [comment]
This is a result of the graphing utility only updating when it sees changes in the encoder position. Plotting stops whenever there is no change and you would see this in any state of operation. This can be changed to always plot when data is received.

**Comment by mbromley-voxel** [comment]
Validated.  Graphing position is continuous
