### ISSUE TITLE
Step Size Parameter

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#29]
Currently the "Step Size" Box will only allow you to entire values base on the first decimal place. We need 3 decimal places as the encoder value can handle increments as small as 0.005 um. A normal step size value is 0.05 um.

**Comment by mbromley-voxel** [comment]
The box displays three decimal places but any value less than 0.1 is rounded down to 0.000 upon entering. @majorpr13

**Comment by majorpr13** [comment]
Rounding error has been corrected.

**Comment by mbromley-voxel** [comment]
Validated
