### ISSUE TITLE
Establish Touchoff Front Panel Issues

### ISSUE THREAD

**Issue by majorpr13** [mbromley-voxel/ECM-Control-System#32]
The establish touchoff button from the front panel was reported to not be connected to anything.

**Comment by majorpr13** [comment]
@mbromley-voxel This button actually works. Its role was only as a shortcut to open the touchoff window, however, if the window was already open but perhaps hidden behind others you wouldn't have seen any actions. This can be changed to reflect perhaps moving to front, however, given the display move you want this button in all likelihood would go away so perhaps I shall remove in the meantime?

**Comment by mbromley-voxel** [comment]
Understood.  Fine to leave as is with the display updates coming.
