### ISSUE TITLE
Touchoff Status Needs Accurate Reflection

### ISSUE THREAD

**Issue by majorpr13** [mbromley-voxel/ECM-Control-System#34]
The status of the touchoff does not change from "Touch-off Searching" if the touch off attempt is cancelled.

**Comment by majorpr13** [comment]
How do we know when we want to reinitialize the touch off status? For example, if the motor is disabled we state the home position is no longer valid, I imagine the touchoff behavior should be the same?

**Comment by mbromley-voxel** [comment]
@majorpr13 that is correct.  Essentially if anything happens (jog, manual movement, motor disable) the touchoff status shoudl change.  It is only valid after performing the touch off routine and not adjusting anything.

**Comment by majorpr13** [comment]
This should now be accurately addressed in the multioperations branch.
