### ISSUE TITLE
New profile does not execute after Stop

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#42]
If I abort a profile execution with the stop button and then select "Run Explicity Profile" to begin running again the pump turns on, but it does not appear that the profile is executed.  No movement is observed and the power supply does not begin pulsing.

**Comment by majorpr13** [comment]
This has been corrected with the stop button command. The issue was stop on axis doesnt terminate the current running program. This was similar to other related issues.

**Comment by mbromley-voxel** [comment]
Validated
