### ISSUE TITLE
Left Electrolyte On After Run

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#46]
I was using a timed run (Motor was stationary, only power supply and electrolyte flow were active) and after the run completed, the electrolyte never turned off.

**Comment by majorpr13** [comment]
@mbromley-voxel when executing a timed run, did the script follow the rules for terminating a run? 
For example, did it emit a completed status code on the cutdone variable?

**Comment by mbromley-voxel** [comment]
I tried again this morning and I could not recreate the error.
