### ISSUE TITLE
Set touch-off ref loading mechanism

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#49]
When you push the "Set Touchoff Ref" position button, it appears that it loads the value from the graph, or some stored value. Can we change that to pull the position using the TP command in galil to ensure an accurate value?

**Comment by mbromley-voxel** [comment]
It seems that the plot (and ultimately the last known position by the software) can lag at times when executing a move.  Therefore when the "Set Touchoff Ref" position button is hit it will record an incorrect value that matches the last known position in the plot.  We will work on getting better defining a repeatable set of operations that causes this issue.

**Comment by majorpr13** [comment]
@mbromley-voxel This would appear to be based on the machine in motion and the request position frequency not being high enough previously. I think the current update rate this would not be an issue. What we could do to make sure is lock these buttons while the machine is in motion?

**Comment by mbromley-voxel** [comment]
@majorpr13 yes I agree that a lock while the machine is in motion would be a good precautionary measure.
