### ISSUE TITLE
ppos shows up on the graph in counts instead of um

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#50]
ppos shows up in counts (is marked as unitless) on the plot and needs to read in um.

**Comment by majorpr13** [comment]
I cannot test this one without executing a profile, however, I believe I have something within the commit that should correct for this. At the moment this is kind of a hack until we get the profile variable constructor completed as I statically listen for and change the ppos status update variables.

**Comment by mbromley-voxel** [comment]
Validated
