### ISSUE TITLE
Software closed during run

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#51]
With no interaction from the user, the software window closed while  a run was in progress. Re-opening the software dropped the motor. It may take some time to diagnose why it closed, but can we add some fail-safes during the programs opening routine to leave the motor in place if it is already on?

**Comment by majorpr13** [comment]
I believe this issue is no longer pertinent.

**Comment by mbromley-voxel** [comment]
@majorpr13 is it possible that the software can crash and leave the motor on? If it does will the motor be disabled upon reopening the software?

**Comment by majorpr13** [comment]
When the software crashes it will leave the motor on in whatever state it was last. Upon reopening the software, yes it is going to disable it and setup the machine again. Did you see it crash?
