### ISSUE TITLE
Software crashed during run

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#57]
This has happened a three times now between today and yesterday.  I recorded a video of the screen when the issue occurred.  It is stored on the desktop under -> Screen Records.  The run was started and a few seconds later the software shut down.  This is a big issue because the machining continues until the software is rebooted.

**Comment by majorpr13** [comment]
The relevance of this issue is no longer pertinent and/or applicable with the current software.
