### ISSUE TITLE
Manual Control Commands will Abort a Profile

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#59]
If the user accidentally or purposely clicks on the manual commands during a profile execution they will override the profile.  It should at the very least pop up a warning that says profile execution in progress, want to continue?

**Comment by majorpr13** [comment]
Ok so you are fine with the profile being aborted...just need to notify the user if they want to continue with the motion command or the profile.

**Comment by mbromley-voxel** [comment]
Correct

**Comment by majorpr13** [comment]
The buttons are locked at this current time when operating a motion profile.
