### ISSUE TITLE
Create a new configuration

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#60]
There is no option currently to open a new clean slate configuration window.  It shows what is currently loaded and only has the option to open another configuration under File.

**Comment by majorpr13** [comment]
So you want a clear all function vs clearing individual profiles?

**Comment by mbromley-voxel** [comment]
Yes.  I just had one with six operations, I want to go to File->New and open up a blank slate

**Comment by majorpr13** [comment]
This has been addressed in the multioperations branch.
