### ISSUE TITLE
Stop during homing routine messes with the state

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#62]
If the user commands a stop during the home routine after a configuration execution the software is very confused.  It does not execute the homing routine the next time you go to execute a configuration.  If the user manual clicks reset home, then the touch off window pops up like it is still in the configuration execution.

**Comment by majorpr13** [comment]
Outer profile state remained in the homing state which had caused the underlying issue. The stop command had not propagated through this portion of the state machine.

**Comment by majorpr13** [comment]
This should have been addressed with the latest commits. @mbromley-voxel can you verify and close?
