### ISSUE TITLE
Configuration Templating for Galil Script Changes

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#63]
When a change is made to the galil script and uploaded all of the variable values in the configuration window are set to the galil defaults.  This requires the user to go back through all of the operations and redo the set up each time.

We need an option to allow changes to be made to the galil script and uploaded without overwriting the parameters already set in the configuration window.

**Comment by majorpr13** [comment]
This should be corrected in the multiops branch of code.
