### ISSUE TITLE
Status bar messages

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#64]
Status bar messages to display critical states/errors.  This includes munk error, touch off errors, etc.

**Comment by majorpr13** [comment]
Messages now have access to the message bar. They are only displayed for a 3 second interval and are overwritten potentially faster if new messages arrive while the current one is being displayed. @mbromley-voxel is this sufficient to close this enhancement? It would appear there is another request to have a rolling history of status messages that perhaps are timestamped that could offer the operator more descriptive output.

**Comment by mbromley-voxel** [comment]
Yes we will take care of the time stamped history with issue #70

**Comment by majorpr13** [comment]
Closing this per the comment above.
