### ISSUE TITLE
status stuck in "touch-off disconnect"

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#66]
Run configuration was selected. After touching off, the run was canceled. The program remained stuck in "touch-off disconnect" state and had to be closed out to become functional again.

**Comment by majorpr13** [comment]
How was the execution canceled? Was the button cancel selected or was the X used (in reference to the pop up window)?

**Comment by mbromley-voxel** [comment]
The cancel button was selected, however we have not yet been able to recreate this condition.  Will update if we can get it to a point that we can recreate.

**Comment by majorpr13** [comment]
Closing as this has no longer seemed pertinent with time.
