### ISSUE TITLE
Operation Starting Position Displayed in Status Bar and Recorded in Log

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#67]
Often times in development we want to record the starting position of the machining profiles.  This position seems to be missed often times in the machine log due to maybe a slight delay in logging.  This request is two fold:

1. After a touch off is complete and before executing the profile request the motors current position and display that position in the status bar.  "Profile starting position:  XXXXX"

2. Record that starting position requested as the first data point in the machine logs.

**Comment by majorpr13** [comment]
This has been completed in the current branch of multiops.
