### ISSUE TITLE
Running log of status bar messages

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#70]
Allow the user to click into the status bar to view a history of the status messages displayed.

**Comment by majorpr13** [comment]
Instead of a status bar opening, can we have a window that is expandable from the primary interface that displays a running log, appropriately timestamped and color coordinated?

**Comment by mbromley-voxel** [comment]
Just what we need... another window...

**Comment by majorpr13** [comment]
It would be apart of the main window...still a showable box...we just dont have more vertical room.

**Comment by majorpr13** [comment]
This is now integrated within the main GUI. Color coding will be a feature request, however, the ACS messages from a profile will have no color coordinating as there is no way to understand the level of severity of the message.
