### ISSUE TITLE
Save Config File with Run Config

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#72]
This should be stored with the Machining Log file.  Save off the config file with a suffix of Part Number - Serial Number.  It should be overwritten each time a configuration is run with the same part number and serial number.  Essentially it will capture the latest configuration run for that part number/serial number.

**Comment by majorpr13** [comment]
A prg file is now also saved with each execution of a profile configuration. This results in a general log file, config file, and prg file upon executing a profile.
