### ISSUE TITLE
Software closes on "run configuration' call

### ISSUE THREAD

**Issue by mbromley-voxel** [mbromley-voxel/ECM-Control-System#74]
Happened two more times today (4/22/19)

**Comment by majorpr13** [comment]
Right so this is what i was expecting. It still believes the machine is moving. You should be able to hit stop to clear it out of this state. I can work on a fix that checks either for motion and/or transmits a stop command before a motion is run.

**Comment by mbromley-voxel** [comment]
hitting the stop button clears the state and lets machining continue

**Comment by mbromley-voxel** [comment]
Would it be possible to add an error pop up if the state is not as needed/expected before executing a call so that the software doesn't just close?  We can work on making it more robust, but there still may be cases where we get it stuck in a state and it would be ideal to not just shut down.

**Comment by majorpr13** [comment]
yeah I can block the close conditions, useful in debug mode as they get caught. I can add notifications that precheck the state before advancing and not shut down. But what you want to do to handle each state is dependent upon the state and the subsequent action you are about to take. We can work out details later but I would need a flow diagram from each state, action, etc on how to handle and mitigate.

**Comment by majorpr13** [comment]
This should no loner be an issue as it blocks the user from doing things in unintended states that would cause this.
